init_pose:
  pose: [0, 0, 0] # x, y, z
  orientation: [0, 0, 0] # roll, pitch, yaw

landmarks:  # x, y, z
  - [4, 4, 0]
  - [4, -1, 0]
  - [3, 0, 0]
  - [3, -4, 0]
  - [2, 2, 0]
  - [1, -2, 0]
  - [1, -4, 0]
  - [0, 3, 0]
  - [-1, -1, 0]
  - [-2, 4, 0]
  - [-2, -4, 0]
  - [-3, 1, 0]
  - [-3, -2, 0]
  - [-4, 4, 0]
  - [-4, 0, 0]

measurement:
  angle_noise: 0.01
  distance_noise: 0.1

simulation:
  loop_period: 0.01
  landmark_measurement_period: 1.0

  linear_speed_coef: 1.0
  angular_speed_coef: 1.0

  sensor_range: 3.0

  visualization_period: 0.05
  ekf_prediction_period: 0.1
